# This file was generated by GoReleaser. DO NOT EDIT.
cask "si" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "si"], chdir: "."
    end
  end

  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "eac49fb5a7a0dc9f0ed429c2010c5db4cffcf79493e946811cea39dd4e4e8555"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "184165bec33ad60a6f81a2177254f84301beb132b6a5cf38a3cf504920b5c60d"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f44be2bba912ac63502217e42c3d6f3922b7863011b34db2fb5780d6a4fc908"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "772ab0489ab6048737858eeafdfb8e972b406f20368faf18e362c769df15603f"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "si"
  desc "Terminal UI for Spring Initializr"
  homepage "https://github.com/osman-butt/spring-init-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "si"

  # No zap stanza required
end
