# This file was generated by GoReleaser. DO NOT EDIT.
cask "si" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "si"], chdir: "."
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "5771521f68c87d7c50145b303a54f3b1ab2566240b59e8dcc4bd2904dbd46d2a"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29c3a94697cec080164ccccb9165481607f98541427a6dd88462a68200b3d135"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc1774a4c8a55258ade6484d86ecdb811b2bb44b56c189801f0721405e827b87"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f5d8dc290757d3d1baf97ea7e8e60928e54f2e9f6d8d2b210650bfbc50b2d10"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "si"
  desc "Terminal UI for Spring Initializr"
  homepage "https://github.com/osman-butt/spring-init-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "si"

  # No zap stanza required
end
