# This file was generated by GoReleaser. DO NOT EDIT.
cask "si" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "766e80e627b8015e73e18e1f91eacedddda71bec2f8dd9121a87a6617074c2ba"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29dcbd2979d188f1862df86712d6144ef355a069b48e409768e216e2fa4a0bae"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "79c12d367384622b5b129e87a8c81bd7e7f78cbfdbc9ac19e04c68ef1ac4ecfb"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "09b173f360e609b51b5e41cef31ab3433a4767bea88905da7e3abc269178d473"
      url "https://github.com/osman-butt/spring-init-tui/releases/download/v#{version}/spring-init-tui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "si"
  desc "Terminal UI for Spring Initializr"
  homepage "https://github.com/osman-butt/spring-init-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "si"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/si"]
    end
  end

  # No zap stanza required
end
